spring:
  application:
    name: statistics-service
  config:
    import:
      - nacos:statistics-service.yaml?serverAddr=127.0.0.1:8848&namespace=Shining&group=Shining
      - nacos:common.yaml?serverAddr=127.0.0.1:8848&namespace=Shining&group=Shining
      - nacos:secret.yaml?serverAddr=127.0.0.1:8848&namespace=Shining&group=Shining
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: Shining
        file-extension: yaml
        group: Shining
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: Shining